//
//  ChildPresenter.swift
//  Send and Recive
//
//  Created by Bhargavi on 20/06/19.
//  Copyright (c) 2019 Amrutha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildPresentationLogic
{
  func presentSomething(response: Child.Something.Response)
  func presentTellParent(response:Child.TellParent.Response)
    
}

class ChildPresenter: ChildPresentationLogic
{
  
    
   weak var viewController: ChildDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Child.Something.Response)
  {
    
    

    let greeting = response.title.isEmpty ? "Hi" : "\(response.title)"
    print(greeting)
    let viewModel = Child.Something.ViewModel(greeting: greeting)
    viewController?.displaySomething(viewModel: viewModel)
  }
    func presentTellParent(response: Child.TellParent.Response) {
        let viewModel = Child.TellParent.ViewModel()
        viewController?.displayTellParent(viewModel: viewModel)
    }
    
 
}
