//
//  ChildViewController.swift
//  Send and Recive
//
//  Created by Bhargavi on 20/06/19.
//  Copyright (c) 2019 Amrutha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ChildDisplayLogic: class
{
  func displaySomething(viewModel: Child.Something.ViewModel)
  func displayTellParent(viewModel: Child.TellParent.ViewModel)
}

class ChildViewController: UIViewController, ChildDisplayLogic
{
 
  
  var interactor: ChildBusinessLogic?
  var router: (NSObjectProtocol & ChildRoutingLogic & ChildDataPassing)?

  // MARK: Object lifecycle
  
  override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
  {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    setup()
  }
  
  required init?(coder aDecoder: NSCoder)
  {
    super.init(coder: aDecoder)
    setup()
  }
  
  // MARK: Setup
  
  private func setup()
  {
    let viewController = self
    let interactor = ChildInteractor()
    let presenter = ChildPresenter()
    let router = ChildRouter()
    viewController.interactor = interactor
    viewController.router = router
    interactor.presenter = presenter
    presenter.viewController = viewController
    router.viewController = viewController
    router.dataStore = interactor
  }
  
  // MARK: Routing
  
  override func prepare(for segue: UIStoryboardSegue, sender: Any?)
  {
    if let scene = segue.identifier {
      let selector = NSSelectorFromString("routeTo\(scene)WithSegue:")
      if let router = router, router.responds(to: selector) {
        router.perform(selector, with: segue)
      }
    }
  }
  
  // MARK: View lifecycle
  
  override func viewDidLoad()
  {
    super.viewDidLoad()
      doSomething()
  }
 
  
  // MARK: Do something
  
  //@IBOutlet weak var nameTextField: UITextField!
   
    @IBOutlet weak var textField: UITextField!
    @IBOutlet weak var label: UILabel!
    @IBAction func onTapPassDataBtn(_ sender: Any) {
        tellParent()
    }
    
  func doSomething()
  {
    let request = Child.Something.Request()
    interactor?.doSomething(request: request)
  }
  func tellParent()
  {
    let data = label.text
    let name = textField.text!
    let request = Child.TellParent.Request(name: data!)
    interactor?.tellParent(request: request)
  }
  func displaySomething(viewModel: Child.Something.ViewModel)
  {
    label.text = viewModel.greeting
    
    //nameTextField.text = viewModel.name
  }
    func displayTellParent(viewModel: Child.TellParent.ViewModel) {
    router?.routeToSomewhere(segue: nil)
    }
}
