//
//  ParentWorker.swift
//  Send and Recive
//
//  Created by Bhargavi on 20/06/19.
//  Copyright (c) 2019 Amrutha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ServerData {
    var title:String {get}
}

class ParentWorker:ServerData
{
    
    var title: String = ""
    var appData:Parent.TellChild.Request?
    
  func doSomeWork()
  {
    var urlRequest = URLRequest(url: URL(string: "https://jsonplaceholder.typicode.com/todos/1")!)
    urlRequest.httpMethod = "GET"
    URLSession.shared.dataTask(with: urlRequest) { (data, resp, err) in
    print(data as Any)
    do{
      self.appData = try JSONDecoder().decode(Parent.TellChild.Request.self, from: data!)
        DispatchQueue.main.async {
         
         if self.appData != nil{
           self.title = self.appData?.title as Any as! String
            print(self.title)
          }
        }
      }catch{
        print("unable to respond")
      }
        
     }.resume()
   }

}
