//
//  ParentPresenter.swift
//  Send and Recive
//
//  Created by Bhargavi on 20/06/19.
//  Copyright (c) 2019 Amrutha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ParentPresentationLogic
{
  func presentSomething(response: Parent.Something.Response)
    func presentTellChild(response: Parent.TellChild.Response)
}

class ParentPresenter: ParentPresentationLogic
{
  
  weak var viewController: ParentDisplayLogic?
  
  // MARK: Do something
  
  func presentSomething(response: Parent.Something.Response)
  {
    let greeting = response.name.isEmpty ? "Hello" : "\(response.name)"
    let viewModel = Parent.Something.ViewModel(greeting: greeting)
    viewController?.displaySomething(viewModel: viewModel)
  }
  func presentTellChild(response: Parent.TellChild.Response) {
    let viewModel = Parent.TellChild.ViewModel()
        
     viewController?.displayGreeting(viewModel: viewModel)
    }
 
  
}
