//
//  ParentRouter.swift
//  Send and Recive
//
//  Created by Bhargavi on 20/06/19.
//  Copyright (c) 2019 Amrutha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ParentRoutingLogic
{
  func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ParentDataPassing
{
  var dataStore: ParentDataStore? { get }
}

class ParentRouter: NSObject, ParentRoutingLogic, ParentDataPassing
{
    
  weak var viewController: ParentViewController?
  var dataStore: ParentDataStore?
  
  // MARK: Routing
  func routeToSomewhere(segue: UIStoryboardSegue?)
  {
    
      let storyboard = UIStoryboard(name: "Main", bundle: nil)
      let destinationVC = storyboard.instantiateViewController(withIdentifier: "ChildViewController") as! ChildViewController
      var destinationDS = destinationVC.router!.dataStore!
      passDataToSomewhere(source: dataStore!, destination: &destinationDS)
      navigateToSomewhere(source: viewController!, destination: destinationVC)

  }

  // MARK: Navigation
  func navigateToSomewhere(source: ParentViewController, destination: ChildViewController)
  {
    source.show(destination, sender: nil)
  }
  
//   MARK: Passing data
  func passDataToSomewhere(source: ParentDataStore, destination: inout ChildDataStore)
  {
    destination.name = source.name
  }
}
