//
//  ParentModels.swift
//  Send and Recive
//
//  Created by Bhargavi on 20/06/19.
//  Copyright (c) 2019 Amrutha. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Parent
{
  // MARK: Use cases
  
  enum Something
  {
    struct Request
    {
    }
    struct Response
    {
        var name: String
    }
    struct ViewModel
    {
        var greeting: String
    }
  }
    enum TellChild {
      struct Request:Codable
      {
        var title: String?
       }
        struct Response
        {
           
        }
        struct ViewModel
        {
           
        }
    }
}
